# This file was generated by GoReleaser. DO NOT EDIT.
cask "linkwise" do
  version "0.1.0"

  on_macos do
    on_arm do
      sha256 "1c0efc5f3387f1b108ce2b302a14d1ae5e8c21a12143da83c80ea38c024678ad"
      url "https://github.com/LinkwiseApp/linkwise-cli/releases/download/v#{version}/linkwise_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "b005ceb679f926e6372e91358704097134d3ba47866096b5d6cb49d5ac75954d"
      url "https://github.com/LinkwiseApp/linkwise-cli/releases/download/v#{version}/linkwise_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "f01a5f4b70fd848e99434e8f8db1cbfaee584d1155fdbfc0f247312ccbfeb693"
      url "https://github.com/LinkwiseApp/linkwise-cli/releases/download/v#{version}/linkwise_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "b5f4a84ba5991fe1d0a14f91ca3a0297c6c04be427b5e7eaae35678fa05216b0"
      url "https://github.com/LinkwiseApp/linkwise-cli/releases/download/v#{version}/linkwise_linux_amd64.tar.gz"
    end
  end

  name "linkwise"
  desc "Your Linkwise library, from the terminal"
  homepage "https://linkwise.app"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "linkwise"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr",
        args: ["-dr", "com.apple.quarantine", "#{staged_path}/linkwise"]
    end
  end

  # No zap stanza required
end
