# This file was generated by GoReleaser. DO NOT EDIT.
cask "linkwise" do
  version "0.1.1"

  on_macos do
    on_arm do
      sha256 "5a90941707481e9d61f44a2582a170e0aaaf4c9927828dd4df613d282b567c9e"
      url "https://github.com/LinkwiseApp/linkwise-cli/releases/download/v#{version}/linkwise_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "eddb720e85552097866a0a720525b7b8c2e71d681d8835f9f1b62f8803ca226a"
      url "https://github.com/LinkwiseApp/linkwise-cli/releases/download/v#{version}/linkwise_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "ebf791691eea44ad033750730a706c707510e130f6b5ecbc51b8e9ae212af804"
      url "https://github.com/LinkwiseApp/linkwise-cli/releases/download/v#{version}/linkwise_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "af712601955a9a36ff2e4b127bc55ff9c8547ec37306e51c42f08f2ae0a2a792"
      url "https://github.com/LinkwiseApp/linkwise-cli/releases/download/v#{version}/linkwise_linux_amd64.tar.gz"
    end
  end

  name "linkwise"
  desc "Your Linkwise library, from the terminal"
  homepage "https://linkwise.app"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "linkwise"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr",
        args: ["-dr", "com.apple.quarantine", "#{staged_path}/linkwise"]
    end
  end

  # No zap stanza required
end
